name: CI/CD Pipeline
on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python -m unittest tests/test_app.py

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}

  deploy-pages:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Create static site
        run: |
          mkdir -p _site
          echo "<h1>Flask App Deployed</h1>" > _site/index.html
          echo "<p>Docker Image: ghcr.io/${{ github.repository }}:${{ github.sha }}</p>" >> _site/index.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Deploy Docker container
        run: |
          echo "Deploying Docker container..."
          echo "Image: ghcr.io/${{ github.repository }}:${{ github.sha }}"
          # Login to container registry
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          # Stop and remove existing container if running
          docker stop flask-app || true
          docker rm flask-app || true
          docker pull ghcr.io/${{ github.repository }}:${{ github.sha }}
          docker run -d -p 5000:5000 ghcr.io/${{ github.repository }}:${{ github.sha }}